name: Scheduler

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #  env:
    #     ChannelAccessToken: ${{secrets.CHANNELACCESSTOKEN}}
      - uses: julia-actions/setup-julia@v1
        run: init.jl
        run: julia PickPopular.jl
