name: Scheduler

# on:
#   schedule:
#     - cron:  '0 0 * * *'

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: set up julia
        uses: julia-actions/setup-julia@v1
    #  env:
    #     ChannelAccessToken: ${{secrets.CHANNELACCESSTOKEN}}
      - name: checkout
        uses: actions/checkout@v1
      - name: exec scripts
        run: |
          pwd
          ls
          julia ./init.jl
          julia ./PickPopular.jl
