name: Scheduler

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: julia-actions/setup-julia@v1
    - run: init.jl
    - env:
        ChannelAccessToken: ${{secrets.CHANNELACCESSTOKEN}}
    - run: julia PickPopular.jl
