name: Scheduler

# on:
#   schedule:
#     - cron:  '0 0 * * *'

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: set up julia
        uses: julia-actions/setup-julia@v1
    #  env:
    #     ChannelAccessToken: ${{secrets.CHANNELACCESSTOKEN}}
      - name: exec scripts
        run: init.jl
        run: julia PickPopular.jl
